### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by anmolcool007**
Improved basic UI.
Added CSS to add more functionality to list designs.

### CODE REVIEW

**Comment by Yash5044** [comment]
Thanks for contributing

**Comment by Tanuj22** [comment]
@anmolcool007 @Yash5044 full hacktoberfest :smiling_imp:

**Comment by Yash5044** [comment]
@Tanuj22 majak nahi udate

**Comment by Tanuj22** [comment]
There should be machanism to report this :smiling_imp:

**Comment by Yash5044** [comment]
I'll give you 5 repos to report in exchange of 1$

**Comment by Tanuj22** [comment]
Discord pe aao

**Pull request merged**
